name: 400FeetUp
favicon: null
layout_spectrum: 0.6725379819981754
typography_spectrum: 0.9241040947381407
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7582068012561649
  lightness: 0.49150517769157887
  saturation: 0.9690051805227995
  rhythmicContrast: 0.09957318799570203
purpose: []
