name: 400FeetUp
favicon: null
layout_spectrum: 0
typography_spectrum: 0.39854
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111510'
    - '#ffffff'
    - '#99bad9'
    - '#48607f'
    - '#7390b0'
  brandStrength: 0
  lightness: 0.49150517769157887
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
